### ISSUE TITLE
Stable released Ver.3.3.8 is something wrong. No Face Maps entry is generated.

### ISSUE THREAD

**Issue by Tsukasa-YAMATO** [JoseConseco/GoB#111] opened 2020-06-18 14:22 UTC
Isn't this a mistake in file management? In stable version Ver.3.3.8, no entry is created in Face Maps. Whereas  beta Ver.3.3.8 (Kromar Verision) And Ver.3.3.9 works correctly. Please check the contents of the file once published at the following URL.

Wrong stable version published below:

https://github.com/JoseConseco/GoB

https://github.com/JoseConseco/GoB/archive/v3_3_8.zip

----

Correct working beta versions I have tested below:

(Kromar Ver.3.3.9)
https://github.com/kromar/blender_GoB/tree/feature/optional-mask-import

(Kromar Ver.3.3.8)
https://github.com/kromar/blender_GoB/tree/feature/clear_mask

Where is the true stable released version's URL link?
(I don't know the detail of dealing with GitHub so please show me clearly the URL whete the stable GoB version is pubulished.) 

P.S.
(I was about to introduce a dangerous imperfect GoB to a friend. It's important to check it previously in case.)

**Comment by kromar** [comment] 2020-06-18 14:55
Uhh thanks for the report i will have a look

**Comment by Tsukasa-YAMATO** [comment] 2020-06-18 15:03
@kromar 
If you confirm the status of the correct file, please write the correct public URL. I'm not quite familiar with GitHub, so I'm not sure where it is correct published URL.
Also, the URL you write will be sent to my friends via social media in the future, so it is very important to confirm that it is in the correct state.

At least I have confirmed that it is correct in every beta version, so I think that the stable version will never become unstable. :)

You don't have to rush into checking it.
Please calm down and do the best woriking!

**Comment by kromar** [comment] 2020-06-18 15:05
i just tested the face map transfer and it seems to work fine for me on the v3_3_8 tag
![image](https://user-images.githubusercontent.com/1472884/85037617-e345f180-b185-11ea-9a68-e303cd7a9a56.png)

i will do a file comparison with the downloaded zip, maybe something went wrong there

**Comment by kromar** [comment] 2020-06-18 15:06
did you download this version from the releases? https://github.com/JoseConseco/GoB/releases

**Comment by kromar** [comment] 2020-06-18 15:12
they seem to be the exact same files so it should be correct. do you maybe have multiple versions installed that might cause some conflicts? when extracting the release it usually creates a folder with the version. 

![image](https://user-images.githubusercontent.com/1472884/85038262-ad553d00-b186-11ea-9754-6833e6bb4559.png)

**Comment by Tsukasa-YAMATO** [comment] 2020-06-18 15:14
I have downloaded it from here.
https://github.com/JoseConseco/GoB

![2020-06-19_00h10_28](https://user-images.githubusercontent.com/65609416/85038257-591b7e80-b1c1-11ea-9d1b-13cf7ffa30d2.jpg)

and also tested from here.

https://github.com/JoseConseco/GoB/archive/v3_3_8.zip

![2020-06-19_00h12_17](https://user-images.githubusercontent.com/65609416/85038591-b9122500-b1c1-11ea-8742-526f3eab38e7.jpg)

**Comment by kromar** [comment] 2020-06-18 15:20
both of these should give you the same versions. but the later one should be the correct release from tag v3_3_8

**Comment by Tsukasa-YAMATO** [comment] 2020-06-18 15:28
I'm using this.
https://github.com/JoseConseco/GoB/archive/v3_3_8.zip

After all it is strange. Transfer Zbrush template Soldier Kneeguard to Blender with GoB. In my environment, no entries are created in Face Maps. Correctly, two entries (2 polygroups) must be created automatically.

![2020-06-19_00h22_27](https://user-images.githubusercontent.com/65609416/85039910-2bcfd000-b1c3-11ea-82ce-e47299ab2c8a.jpg)

Could you reproduce it in your environment?

**Comment by kromar** [comment] 2020-06-18 15:35
this is strange, i can not reproduce it. can you check if you get any errors in the command line?
![image](https://user-images.githubusercontent.com/1472884/85041318-0ffc0800-b18a-11ea-93e0-f5ecef8fa1ad.png)

**Comment by Tsukasa-YAMATO** [comment] 2020-06-18 15:41
What! It's very strange. Restart my windows PC and I will also test it with Blender 2.82a, 2.83 and Zbrush 2020.1.3, 2020.1.4. Please wait for a little while.

I will use this.
https://github.com/JoseConseco/GoB/archive/v3_3_8.zip

**Comment by Tsukasa-YAMATO** [comment] 2020-06-18 15:59
I tried installing GoB release version to 2.82a for the first time. Face Maps was created successfully. When I looked at the environment settings, I noticed that Clear Mask was turned off. On the other hand, it was ON when I was testing it with 2.83. There may be some hints here. I will try a little more.

![2020-06-19_00h55_37](https://user-images.githubusercontent.com/65609416/85044070-1c06ba80-b1c8-11ea-9750-37799505d999.jpg)

**Comment by Tsukasa-YAMATO** [comment] 2020-06-18 16:15
@kromar 
In any case, the fact that 2.82a is normal in my environment and 2.83 is abnormal in my environment is very likely to be my environmental problem. I will try to find the cause. I will comment if I understand the cause. (Maybe it's no problem for many users, but it's possible that it may be worth the information.)
I will write again in a few hours or days.

Please put it on hold and take a rest.

**Comment by Tsukasa-YAMATO** [comment] 2020-06-18 16:45
@kromar 
Dear Daniel,
I fully understood the cause. I will report the details again tomorrow. Because Japan is about 2 
 A.M. and I'm very sleepy :) 
Simply put, this is a matter of my environment. However, it is a phenomenon that can occur even for users who have been using GoB add-ons for a long time.

The bottom line is, "Once you completely remove the GoB add-on from Blender!" this is the answer. And everything works the best.

I don't know in detail, but it seems that GoB's past data, that is, cache file, is doing something wrong with Blender. So if you erase it, all will be solved.

Details will be reported later.
(This may be important for long time GoB lovers.)

**Comment by Tsukasa-YAMATO** [comment] 2020-06-19 08:12
@kromar 
In my case, it seems that the "some data that cannot be rewritten by replacing the file in the GoB folder" such as the Blender cache file was doing a bad thing.
Because during the beta test, I was always swapping all the files in the GoB folder. And during the beta test there was no problem. However, when I applied this working process to the stable version, the above strange phenomenon occurred.

So, once I cleanly deleted the GoB add-on from Blender and then re-installed the Zip file, it worked fine.
And at the time of uninstalling, the first deletion couldn't be completed neatly due to an error. This was a hint. When I restarted Blender and searched for GoB add-on, I found that some data remained after the first deletion, and I found it. I removed it again and restarted Blender in order to make sure I didn't have GoB in Blender. And I reinstalled it and it's working well.

![2020-06-19_16h51_01](https://user-images.githubusercontent.com/65609416/85111220-0092c280-b24f-11ea-8c12-ff3637c5161f.jpg)

Here, put the screenshot image of the preferences when the correcrt GoB Ver.3.3.8 was clean installed. If it is in any other check box state, it is highly possible that GoB is not updated properly because old data remains in Blender. (And it leads to mysterious behavior that isn't in the spec. It's horrifying enough to bother developers :))

![2020-06-19_16h44_31](https://user-images.githubusercontent.com/65609416/85111497-62ebc300-b24f-11ea-8ee7-6408315c718a.jpg)

Anyway, I found out that the stable version of GoB Ver.3.3.8 has no problem, and the problem in my environment was cleared, so I will finally introduce Ver.3.3.8 to my friends.

Thank you for releasing GoB!

**Comment by kromar** [comment] 2020-06-20 14:50
Very strange that this happend, i can no think of a reason this should happen if the files are overwritten. I will close this for now and if it happens to more people i will do some more testing on this.

**Closed by kromar** 2020-06-20 14:50 UTC

**Comment by Tsukasa-YAMATO** [comment] 2020-06-20 14:58
I also don't know the cause when thinking logically. However, I got an error when deleting the first GoB addon. (I forgot to take the screenshot.) After that, I uninstalled GoB again, and then reinstalled the newer GoB again and then it worked well, so it's a mystery.
However, since there is no doubt that the above procedure made correct working, I decided to leave a history above, hoping it would be helpful for something.

**Comment by kromar** [comment] 2020-06-20 15:35
Yes it is for sure, i plan to update the documentation and add a troubleshooting section since there have been quite a few scenarios  in the past that caused issues so i think its a good idea to provide a troubleshooting guide of some sort.

**Comment by Tsukasa-YAMATO** [comment] 2020-06-20 15:41
I think that is good. I hear that some of my friends have had a hard time swapping GoB addons. I think the point is "complete uninstall". If users can do that, a fresh re-install will be fine easily.
