### ISSUE TITLE
Blender 2.91 Alpha with GoB (MacOS)

### ISSUE THREAD

**Issue by mac4kent** [JoseConseco/GoB#160] opened 2020-08-26 06:10 UTC
Blender 2.91 Alpha with GoB
https://builder.blender.org/download/
Need fix GoB Syntax error I show you picture
<img width="1500" alt="Screen Shot 2020-08-25 at 11 05 54 PM" src="https://user-images.githubusercontent.com/4253305/91267367-14174980-e728-11ea-9e06-a610fc25ef7d.png">

**Comment by kromar** [comment] 2020-08-26 14:44
thanks for the report, can you tell me which version of the addon caused this error?

**Comment by mac4kent** [comment] 2020-08-26 21:08
I give you link exactly you need get download ox 2.91 alpha

**Comment by kromar** [comment] 2020-08-26 23:44
You did not write the version of the GoB addon.

**Comment by mac4kent** [comment] 2020-08-26 23:48
Ok GOB version:
![image](https://user-images.githubusercontent.com/4253305/91367675-f3003880-e7bb-11ea-8123-aa0910a0f406.png)

**Comment by mac4kent** [comment] 2020-08-28 01:12
Did you get it I show you GOB version?

**Comment by kromar** [comment] 2020-09-01 18:25
ah yes thanks, i got another report regarding the same issue. since i do not have a MacOS its hard to fix it but i should get a system this week so i can hopefully reproduce this issue.

**Comment by kromar** [comment] 2020-09-01 18:29
please use the latest release until i am able to fix this
https://github.com/JoseConseco/GoB/releases

**Comment by kromar** [comment] 2020-09-01 18:52
i tried to fix this issue, would be great if you could see if this takes you a step further. expect more issues since macosx in this version is untested but would be great to work them out.

v3, 4, 82
https://github.com/kromar/blender_GoB/tree/bugfix/filter-for-zbrush-executable

**Comment by mac4kent** [comment] 2020-09-01 19:50
I just click [√] appear it work for sure on Blender 2.91 Alpha congratulation.
I am use MacOS 11 Big Sur.

I let you know Blender are work on code to fix for object cube preview find for mac to appear texture. I figure so hard since few years until I found then I send report ticket to Blender. They don’t understand and I told them over again, over again until other person work on Blender and they understand and got it. Now they work on it with object .obj will appear texture through .mit.

**Comment by kromar** [comment] 2020-09-05 13:32
@mac4kent have you been able to send objects over to zbrush with this version? tha would be great news since it would mean that the changes i did are working!

yeah it can take a while to get some things fixed on blender, but i can understand that with all the requests they get from the community and all the things they want to get done. And they do a really great job improving it on so many areas so i can live with a bunch of cosmetic issues^^ (not sure if yours fits in that category)

**Comment by mac4kent** [comment] 2020-09-05 13:35
Yes I haven’t take test zBrush 2021 and Blender 2.91 yet but 2.91 it work while check box turn on with Add-ons it work on Blender 2.91 Alpha

Wait until they fix .obj before update GoB because there mistake syntax code of .MIT on .obj. I have Macintosh Finder already have preview I can tell.

**Comment by kromar** [comment] 2020-09-05 13:44
i do not use the .obj format for transferring objects i use the pixologic .goz format so i dont think i need to update anything for that fix.

**Comment by mac4kent** [comment] 2020-09-05 14:00
Oh really

**Comment by kromar** [comment] 2020-09-27 19:37
@mac4kent  
please give this new version a try and let me know if you got any issues

v3.4.9
https://github.com/kromar/blender_GoB/tree/bugfix/fixmacos

**Comment by mac4kent** [comment] 2020-09-27 20:24
Sure

**Comment by mac4kent** [comment] 2020-09-27 20:49
You forget to put about Mac direct
I can’t find Mac direct on Blender folder.

**Comment by kromar** [comment] 2020-09-27 21:25
what do you mean with Mac direct?

**Comment by mac4kent** [comment] 2020-09-27 22:25
Example: ~/Library/Application Support/Blender/2.9 this folder also zBrush where folder too

**Comment by mac4kent** [comment] 2020-09-28 16:22
Did you understand about Mac direct folder?

**Comment by kromar** [comment] 2020-09-28 18:10
are you referring to the fact that other apps on mac are one file and not like zbrush a folder?

![Screenshot 2020-09-28 at 20 06 09](https://user-images.githubusercontent.com/1472884/94469496-80bdb200-01c6-11eb-9225-b7b656b059f5.png)

**Comment by mac4kent** [comment] 2020-09-28 18:37
I mean Blender folder I don’t know where to put Preferences > Blender GoB buttonm

**Comment by kromar** [comment] 2020-09-28 18:41
sorry i do not understand, can you maybe try to show it in a screenshot?

**Comment by mac4kent** [comment] 2020-09-28 21:06
Did you see screenshot on Blender folder?

**Comment by kromar** [comment] 2020-09-29 06:56
yes i see that screenshot, but cant see anything out of the ordinary

**Comment by mac4kent** [comment] 2020-09-29 16:34
I see Windows have direct and miss about Macintosh too. I don’t know where to put Blender folder into zBrush 2021 some where for Goz/Gob

**Comment by kromar** [comment] 2020-10-02 20:56
im still not sure i understand. 
With the new version you do not need to put any Blender folder into zbrush. That is done by the GoB addon when you export from blender for the first time which is now the first thing you should do after installing it to get things ready.
Here you can find the installation instructions for the new version:  https://github.com/JoseConseco/GoB/wiki/Installation

**Comment by mac4kent** [comment] 2020-10-03 05:21
I see 3.3.8 GoB I follow your direct click download.
Also I confused where click download too.
https://youtu.be/qAsagcLibY0

**Comment by kromar** [comment] 2020-10-03 07:47
aha, you mean the direct link on the release page for the latest version? since it has such a big update i wanted to get it working on MacOS before i create a release, now that it seems to be working i can create one.

**Comment by mac4kent** [comment] 2020-10-03 17:32
Alright may I have link to get download right one.
Yes direct link on the release page for Mac.

**Comment by kromar** [comment] 2020-10-03 21:48
here is the direct link for the latest version: v3.4.9 
https://github.com/JoseConseco/GoB/archive/GoZ-Blender_28.zip

**Comment by mac4kent** [comment] 2020-10-04 00:10
https://youtu.be/qAsagcLibY0 <https://youtu.be/qAsagcLibY0> (3.3.8) Auto open zBrush after click export
https://youtu.be/GFpW6iFnhDg <https://youtu.be/GFpW6iFnhDg> (3.4.9) error export click.

**Comment by kromar** [comment] 2020-10-04 09:24
Hi,
this is not a error, this window will show when the path to the ZBrush.app is not defined 
![image](https://user-images.githubusercontent.com/1472884/95011826-d74a4680-0633-11eb-808f-3861452219db.png)
Select the ZBrush.app in that window.

It seems that this causes some confusion since there is no explanation when this window pops up and it can be seen as export folder instead of the selection for the executable/app.

**Comment by mac4kent** [comment] 2020-10-04 16:57
Oh well you are use Windows. Mac and Windows is different.
You have to inspect on Mac please. Do not use Windows.
There still error on latest version. 
3.3.8 already auto search and found zBrush itself without I do manual search direct.
See YouTube same thing you see. Please don’t use Windows.
https://youtu.be/7PdgTQMjYFQ

**Comment by kromar** [comment] 2020-10-04 19:55
i tested it on a mac. press accept once you are inside that ZBrush.app folder., that should work.
i think its a limitation of blender that it shows .app files as folders, i will open a bug report for that

**Comment by mac4kent** [comment] 2020-10-04 20:13
Yes correct. That start come from year 2000 MacOS 10.0.0 the biggest change from Year 1983 to 2001 System 1.0.0 to MacOS 9.2.2

They start folder then put extension .app (add) become to be application.
Right click appear and “Open Package Contests”.
Also you can remove .app make become to be folder.
https://youtu.be/3ra7NaWgMwQ <https://youtu.be/3ra7NaWgMwQ>
https://youtu.be/5zBco_4IUSY <https://youtu.be/5zBco_4IUSY>

Please copy from 3.3.8 is best auto search to open zBrush app itself to put new latest version GoB Add-Ons

**Comment by kromar** [comment] 2020-10-04 20:25
im not sure i can get the auto search back due to the changes needed to fix the import problems of the official pixologic import. i will see if its somehow possible.

**Comment by mac4kent** [comment] 2020-10-04 20:33
Sure.

**Comment by kromar** [comment] 2020-10-09 10:50
there is a fix on its way for the .app issues:D tahnks for pointing it out
https://developer.blender.org/D9162

**Comment by mac4kent** [comment] 2020-10-09 16:04
Oh ok thank you for let me know.

**Closed** 2020-12-11 23:23 UTC
Labels: bug, osx, v3_5

**Comment by mac4kent** [comment] 2020-12-11 23:50
No problem. I am on Blender 2.92 Alpha it work to find zBrush.app on manual open file without automatic.
