### ISSUE TITLE
Almost all export files from Blender to ZBrush fails

### ISSUE THREAD

**Issue by twlgerm** [JoseConseco/GoB#475] opened 2024-05-14 07:40 UTC
Python: Traceback (most recent call last):
  File "C:\Users\User\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\GoB-4_0_3\GoB.py", line 1477, in invoke
    bpy.ops.scene.gob_export(as_tool=as_tool)
  File "C:\Program Files\Blender Foundation\Blender 4.0\4.0\scripts\modules\bpy\ops.py", line 109, in __call__
    ret = _op_call(self.idname_py(), kw)
RuntimeError: Error: Python: Traceback (most recent call last):
  File "C:\Users\User\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\GoB-4_0_3\GoB.py", line 1391, in execute
    self.exportGoZ(PATH_GOZ, context.scene, obj, f'{PATH_PROJECT}')
  File "C:\Users\User\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\GoB-4_0_3\GoB.py", line 998, in exportGoZ
    color = active_color.data[loop.index].color_srgb
IndexError: bpy_prop_collection[index]: index 488900 out of range, size 488900
Location: C:\Program Files\Blender Foundation\Blender 4.0\4.0\scripts\modules\bpy\ops.py:109

**Comment by goodstout** [comment] 2024-05-15 05:18
Just seconding this and giving my own error.

![image](https://github.com/JoseConseco/GoB/assets/9341651/db439fa8-a8ad-4ea5-8c77-25ac2c83e0a9)

**Comment by kromar** [comment] 2024-05-15 19:30
Thanks for reporting, i am not able to reproduce this so it would be great to get the exact steps to reproduce the error or a blend file which causes it.

**Comment by kromar** [comment] 2024-05-15 21:31
i have a potential fix for this issue, would be great if you could give this a try
https://github.com/kromar/blender_GoB/tree/fix-vertex-color-out-of-range

**Comment by goodstout** [comment] 2024-05-16 03:44
@kromar  Fix seems to work! Sent a polymesh 3d to Blender, tweaked it, sent it back to Zbrush. I'll pipe back up if i run into any more bugs. Great work!
![image](https://github.com/JoseConseco/GoB/assets/9341651/b6f90ffe-8e1a-45d4-9d08-a765cf05800f)
![image](https://github.com/JoseConseco/GoB/assets/9341651/62cae5a6-4fc1-4868-a3f2-989953087106)

**Comment by JinStary** [comment] 2024-05-16 17:20
![image](https://github.com/JoseConseco/GoB/assets/100673636/a6942f22-5647-45a0-8654-4a12358ae254)
I also encountered this problem. zbrush2022.08, blender4.1, GoB4.0.3.
The specific reproduction is that ZBrush can GoB to Blender. If Blender only modifies the vertices of the model (rather than moving the model), it can GoB back to ZBrush correctly. However, if the model is moved in Blender, GoB will report an error when GoB returns to ZBrush.

**Comment by JinStary** [comment] 2024-05-16 17:36
@kromar Your fix works!

**Comment by kromar** [comment] 2024-05-16 20:00
I did some more changes and made that part a bit faster. Would be great to get some more confirmation on this before i make a new release with it.
https://github.com/kromar/blender_GoB/tree/fix-vertex-color-out-of-range

**Comment by twlgerm** [comment] 2024-05-16 21:58
> Thanks for reporting, i am not able to reproduce this so it would be great to get the exact steps to reproduce the error or a blend file which causes it.

Hi, apologies for the late reply. I am fairly new tro GitHub and all these and didn't realize the thread was going on here.
I tried your latest change and it seems like the error stopped occuring. However, nothing happens after I export. There is no continuation between Blender and ZBrush after hitting the export button. The program seems to repond and freeze for a while but once it starts moving again nothing changes. I checked scripting to see if there were any errors and it's clean as a whistle.
As for reproducing, I can't really say much. I generated a UV sphere, sculpted and remeshed it, and then attempted to export the object but it generally fails. Usually importing from ZBrush works though, it's always exporting that has issues

**Comment by twlgerm** [comment] 2024-05-16 22:02
Also, interestingly enough, I took the model that I sucessfully imported from Zbrush, moved the verts a little, and then attempted to export it back to ZBrush but the same thing happened: The add on thinks for a while and then nothing happens. No errors.

**Closed** 2024-05-19 09:38 UTC
Labels: bug, color attributes

**Comment by kromar** [comment] 2024-05-19 11:16
@twlgerm do you have the maxon version of zbrush? I have some work to fo to support the maxon paths to fix your issue.

**Comment by twlgerm** [comment] 2024-05-19 15:19
> @twlgerm do you have the maxon version of zbrush? I have some work to fo to support the maxon paths to fix your issue.

I am not sure, I'm just using ZBrush 2022 so I would think not. Should I start from removing all trace of GoB and starting again?
