### ISSUE TITLE
One way only :-(

### ISSUE THREAD

**Issue by lukedor** [JoseConseco/GoB#55] opened 2019-11-26 10:09 UTC
On ZBrush 2019.1 & Blender 2.8, both ways worked perfectly.
But after update to Zbrush 2020, working only way: Zbrush -> Blender.
In Blender, after selected mesh and push "Export", autoswitched to ZBrush and thats all.
Mesh not exported.
GOB v 3.0.91
Reinstall All … The Same problem.
Sorry so much. Very usefull Bridge.

**Comment by nuzzar** [comment] 2019-12-11 06:49
Did you also update Blender? I also experienced this issue when I updated Blender to 2.81a. I'm not sure if this is related but I fixed it by changing the path to new Blender path in the GoZ_Config.txt (The one in the public folder)

**Comment by kromar** [comment] 2019-12-11 08:36
i have not encountered this issue and its really not enough information to do anything about it. others had this problem as well but seemed to resolve itself once a export was done from blender. unless there are some errors or some reproducible scenario i really cant help with this:(

**Comment by nuzzar** [comment] 2019-12-11 19:00
In my case the blender 2.81a installer put the blender.exe under its own Blender 2.81 folder (usually the installer put it under Blender folder, not sure why perhaps it's a new thing or because of what I did since I have several Blender version installed), this is what breaks GoB setup since the the GoZ_Config.txt points to the Blender folder not Blender 2.81 folder. I don't need a fix for this, just want to help OP.

**Comment by lukedor** [comment] 2019-12-11 23:02
GoZ_Config.txt has the right path to the blender 2.81. 
The problem is not in the blender versions,
It started after i uninstalled ZBrush19.1 and installed ZBrush2020 (with a subsequent reinstallation of the GOB plugin).
ZBrush finds Blender (2.80, 2.81) and transfers the grid perfectly.
Blender also finds Zbrush 2020 (because after select mesh & clicking "Export", the ZBrush interface opens), but cannot transmit the geometry.

**Comment by lukedor** [comment] 2020-03-09 10:03
I completely removed everything concerning the blender 2.81 and installed the new version 2.82 on another drive(E:\). Now GOB works in both directions.
Thank you for a very useful bridge!
With best regards.

**Comment by kromar** [comment] 2020-03-09 15:21
glad to hear that you found a solution to this.

**Closed by kromar** 2020-03-09 15:21 UTC
Labels: bug
