### ISSUE TITLE
Cannot export in mac

### ISSUE THREAD

**Issue by Ojas-dev** [JoseConseco/GoB#265] opened 2021-09-17 11:17 UTC
Whenever I click export this error thing is coming:
![Screenshot 2021-09-17 at 4 45 58 PM](https://user-images.githubusercontent.com/61822816/133773968-3874b1b8-79ea-47e8-8cc8-006cb29d8ea6.png)
Any fixes????
(I'm using Blender 2.93.4 BTW and MacOS catalina if that helps :)

**Comment by kromar** [comment] 2021-09-19 19:36
can you try to run the GoZ installer and see if that fixes the issue?

**Comment by Ojas-dev** [comment] 2021-09-21 11:11
Nope still does not seem to work It is giving the same error

**Comment by kromar** [comment] 2021-09-26 10:55
i will need to fire up my mac to see if i can reproduce this then.

**Comment by Ojas-dev** [comment] 2021-09-28 04:42
OK! hope it is easy to fix :)

**Comment by kromar** [comment] 2021-09-28 20:08
it was very easy to fix:D this should do it:
v 3.5.65
https://github.com/kromar/blender_GoB/tree/fix-paths

**Comment by DanteSanbel** [comment] 2021-10-07 08:57
Hi there! Can you help me fix it? I get the same error

**Comment by DanteSanbel** [comment] 2021-10-07 22:04
<img width="1438" alt="Captura de Pantalla 2021-10-07 a la(s) 17 02 35" src="https://user-images.githubusercontent.com/92085287/136468292-8c0d1415-d8f5-432f-92d9-9ee2c682ea9c.png">

No, the same appears to me
Could it be because I am occupying macOS Big Sur?

**Comment by rgbxyz** [comment] 2021-12-16 04:30
Any update on export for Mac? I'm getting a similar error with the current release too. 
I can go from Zbrush to Blender but not the other way around.

**Comment by kromar** [comment] 2021-12-25 21:48
not yet, i dont have much time at the moment to work on the addon. i will see that i can prioritize this one.

**Comment by kromar** [comment] 2021-12-26 12:43
@rgbxyz can you post the error you get and the exact steps you are doing to get it? i am not able to reproduce any errors on my side so its impossible to fix without any further details.

**Comment by rgbxyz** [comment] 2021-12-27 05:04
Thanks for looking into this again and all the effort put into GoB.
I've tried installing the AddOn following the ReadMe instructions as closely as possible since I thought the path or GitHub zip file name changes might be part of the problem, but still no luck.

Steps for repro are: Create geometry in Blender, press Zexport button and the error pops up immediately.

"Python: Traceback (most recent call last):
  File "/Users/*_username_*/Library/Application Support/Blender/3.0/scripts/addons/JoseConseco-GoB-407bade/GoB.py", line 1267, in invoke
    bpy.ops.scene.gob_export(as_tool=as_tool)
  File "/Applications/Blender.app/Contents/Resources/3.0/scripts/modules/bpy/ops.py", line 132, in __call__
    ret = _op_call(self.idname_py(), None, kw)
RuntimeError: Error: Python: Traceback (most recent call last):
  File "/Users/*_username_*/Library/Application Support/Blender/3.0/scripts/addons/JoseConseco-GoB-407bade/GoB.py", line 1064, in execute
    shutil.copytree(source_GoZ_Info, target_GoZ_Info, symlinks=True)            
  File "/Applications/Blender.app/Contents/Resources/3.0/python/lib/python3.9/shutil.py", line 565, in copytree
    return _copytree(entries=entries, src=src, dst=dst, symlinks=symlinks,
  File "/Applications/Blender.app/Contents/Resources/3.0/python/lib/python3.9/shutil.py", line 466, in _copytree
    os.makedirs(dst, exist_ok=dirs_exist_ok)
  File "/Applications/Blender.app/Contents/Resources/3.0/python/lib/python3.9/os.py", line 225, in makedirs
    mkdir(name, mode)
FileExistsError: [Errno 17] File exists: '/Users/Shared/Pixologic/GoZApps/Blender/'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/*_username_*/Library/Application Support/Blender/3.0/scripts/addons/JoseConseco-GoB-407bade/GoB.py", line 1068, in execute
    shutil.copy2(source_GoZ_Info, target_GoZ_Info)  
  File "/Applications/Blender.app/Contents/Resources/3.0/python/lib/python3.9/shutil.py", line 444, in copy2
    copystat(src, dst, follow_symlinks=follow_symlinks)
  File "/Applications/Blender.app/Contents/Resources/3.0/python/lib/python3.9/shutil.py", line 383, in copystat
    lookup("utime")(dst, ns=(st.st_atime_ns, st.st_mtime_ns),
PermissionError: [Errno 1] Operation not permitted

location: /Applications/Blender.app/Contents/Resources/3.0/scripts/modules/bpy/ops.py:132



location: <unknown location>:-1"

**Comment by kromar** [comment] 2021-12-29 14:04
@rgbxyz i am not able to reproduce this error, it would be great if you could try what i described in this ticket to reset the zbrush GoZ installation and see if this also fixes your issue.:
https://github.com/JoseConseco/GoB/issues/275

i have a version with soem minor fixes and support for the GoZ installation button so would be good if you could try it from this version: 3.5.70
https://github.com/kromar/blender_GoB/tree/macos-zsh

**Comment by spencersmb** [comment] 2022-04-21 04:57
I tried following the steps and have run into the same error. Tried Goz reinstall - Zbrush shows blender as a GOZ path, but nothing happens when I try to GOZ from Zbrush. I see the export/import/manual from Blender but pressing any of them I get the error. Any Ideas?

MacOS: Monterey 12.3.1
Blender: 3.1.2
Zbrush: 2022.0.5

**Comment by kromar** [comment] 2022-05-16 20:40
@rgbxyz thanks for reporting this, it seems that error was not related to the other reports here but a issue when you tried to send a mesh from edit mode when it does not have a modifier, this should be fixed in this version: 
v3_5_74 
https://github.com/kromar/blender_GoB/archive/refs/heads/prevent-export-scale-change.zip
https://github.com/kromar/blender_GoB/tree/prevent-export-scale-change
it would be great if you could let me know if you still encounter this issue.

**Closed** 2022-06-28 07:51 UTC
Labels: bug
