### ISSUE TITLE
Blender 3.5 does not export vertex colors to ZBrush

### ISSUE THREAD

**Issue by FatCatArt** [JoseConseco/GoB#412] opened 2023-04-22 13:11 UTC
I have noticed that Blender 3.5 does not export vertex colors to ZBrush. When I export a model with vertex colors from Blender to ZBrush, the vertex colors are not preserved in the exported file. In Blender 3.4 it works just fine.

**Comment by brandonlafrance** [comment] 2023-07-27 22:27
I'm also experiencing this issue, a fix would be great. If you need any additional information or help reproducing this, please reach out! Thanks for all the hard work!

**Comment by kromar** [comment] 2023-08-22 19:52
I can not reproduce this, please provide detailed information on the addon settings and the steps to reproduce this issue.

**Comment by brandonlafrance** [comment] 2023-08-22 20:43
> I can not reproduce this, please provide detailed information on the addon settings and the steps to reproduce this issue.

Thanks for looking into this!

I'm on Blender 3.6.1, ZBrush 2023.1, GoB 3.5.92, and Windows 10. Plugin settings below.

![image](https://github.com/JoseConseco/GoB/assets/9202736/72280fdd-a162-44dc-bf7e-f1eb44946361)

All other functions seem to work as expected. Steps to reproduce:

1. Open a new scene
2. Select the default cube
3. Enter Vertex Paint Mode
4. Apply a vertex color to the entire object
5. Press "Export" button

Cube is imported into ZBrush, but no Polypaint data is transferred.

Blender, by default, names the mesh's Color Attribute as simply, "Attribute". Renaming the attribute to "Col" does not seem to have any effect.

**Comment by kromar** [comment] 2023-08-23 21:48
Thanks for the details, i was able to reproduce the issue.
I made a fix for the vertex colors, would be great if you could see if it works for you

v3.6.0
https://github.com/kromar/blender_GoB/tree/fix-vertex-colors
https://github.com/kromar/blender_GoB/archive/refs/heads/fix-vertex-colors.zip

**Comment by brandonlafrance** [comment] 2023-08-24 19:20
@kromar After a bit of testing, it looks like Vertex colors are getting transferred now. Huzzah!

This may be a different bug, but I did notice some weirdness where some values were being imported incorrectly, I think due to the way Polypaint is per vertex, whereas color attributes in Blender are set to "Face Corner" by default. Changing the color attribute from "Face Corner" to "Vertex" seems to fix this inconsistency on import, however exporting throws this error:

![image](https://github.com/JoseConseco/GoB/assets/9202736/e4b7001a-f29d-4a0a-8bc3-a9cd92fc82ef)

**Comment by brandonlafrance** [comment] 2023-08-24 19:29
Just wanted to add that the inconsistency described above is easiest to observe on the default cube where the corners share different colors. My method to reproduce:

1. In Blender, set vertex color to red
2. Export
3. In ZBrush paint only half verts blue
4. GoZ

This is probably less noticeable on more complex geometry.

Also one final note, I'm not sure if this is something you fixed since your last post, but it appears that the imported vertex color is being applied to the active color attribute, which is nice.

**Comment by kromar** [comment] 2023-08-26 17:09
i pushed a fix for the export issue, let me know if you still have issues with this
https://github.com/kromar/blender_GoB/tree/fix-vertex-colors
https://github.com/kromar/blender_GoB/archive/refs/heads/fix-vertex-colors.zip

**Comment by brandonlafrance** [comment] 2023-08-29 17:45
@kromar Tested your fix, and it looks like everything is working as expected! Thanks a ton for all of your help! Is there any way I can buy you a coffee and/or beer?

**Comment by kromar** [comment] 2023-09-03 09:40
> @kromar Tested your fix, and it looks like everything is working as expected! Thanks a ton for all of your help! Is there any way I can buy you a coffee and/or beer?

Im happy to hear that it works now! Thanks for reporting /contributing to the issue, it makes the work a lot easier! 
Sure here you can buy me a coffee:D https://ko-fi.com/kromar

**Comment by miaumori** [comment] 2023-09-04 13:45
hellow, im on blender 3.6.2 and addon ver 3.6.1. ZBrush ver 20234 build #28 when im exporting to ZBrush my mesh vertex colour are wrong, i dont know why though

my colours in blender:
![изображение](https://github.com/JoseConseco/GoB/assets/90697505/87a0d002-0d2a-46db-9799-a5d673a19dce)

exported to zbrush:
![изображение](https://github.com/JoseConseco/GoB/assets/90697505/41fbeaa2-2242-48ef-8f61-80c281b3be61)

**Comment by kromar** [comment] 2023-09-04 20:20
> hellow, im on blender 3.6.2 and addon ver 3.6.1. ZBrush ver 2023 build 28, when im exporting to ZBrush my mesh vertex colour are wrong, i dont know why though

hm that does not look right, is it possible for you to share a model which i can use to reproduce the issue?

**Closed** 2023-09-30 08:05 UTC
Labels: bug
