### ISSUE TITLE
vertex weights not transferred

### ISSUE THREAD

**Issue by kromar** [JoseConseco/GoB#99] opened 2020-05-27 19:16 UTC

**Comment by Tsukasa-YAMATO** [comment] 2020-06-02 15:38
(It would be great to be able to process a mesh rigged with Blender on Zbrush while maintaining weight information! But that may be difficult.)

Is it really a bug? Isn't it possible that the specifications may not be realized, is it?

Below are my predictions.
The vertex groups outputted by Blender probably will have the correct weight information. Zbrush receives it and the user performs brushing to change the position of the vertices. Then users will use GoB to send back the mesh to Blender.

The question is whether Zbrush "correctly includes the original weight information" in the intermediate generated file that Zbrush will send to Blender.

As you know, Zbrush has no bones or weight information. Is Zbrush really "correctly returning all the information including the data which Zbrush will never use "? I doubt.

Mr. Jose, please check the content of the intermediate generated file.
(Use GoB Ver.3.3.6 because Ver.3.2.5 shutdown Blender when GoB import from Zbrush, it’s a bug.)
(And also Ver.3.3.6 has a bug in Step 2, be careful.)

![2020-06-03_00h19_04](https://user-images.githubusercontent.com/65609416/83539239-c11b6500-a531-11ea-9a3d-c169831fea82.jpg)


1. Create a mesh with bones and weights in Blender
2. Be sure to add a Face Maps entry that applies all the vertices to "Face Maps" for that mesh (Zbrush will shutdown without this, a bug.)
3. Brushing on Zbrush (However, do not change the topology. Only add a brushing that changes only the positions of vertices. E.g. using only standard brush or smooth brush.)
4. Press GoZ button (Execute GoB from Zbrush to Blender)
5. Check if the intermediate generated file outputted by Zbrush (the file that will be imported into Blender) really includes the original weight information.

If the weight information is reset to 0 or  has been deleted in step 4, nothing we can do. Obviously information that does not exist cannot be imported into Blender.

**Comment by Tsukasa-YAMATO** [comment] 2020-06-02 19:19
Hi, Mr. Kromar, I'm verry sorry. I've completely mistaken that you are Mr. Jose from the project name.

Thank you for the detailed explanation. There are some parts that I don't understand about multi-layers and polygroups, but I'm glad to know that the vertex weight information may be retained.

If the weight information I have set in Blender would be preserved when I send the mesh back again from Zbrush to Blender, It would be great!!! (Of course only if the topology doesn't be changed. For corresponding to vertex number and weight information.)

1. Create a rigged person model in Blender
2. Try posing
3. Increase mesh density with multi-resolution modifier
4. Export GoB to Zbrush
5. Sculpt with Zbrush
6. Creators will want to fine-tune the posing while sculpting
7. Import into Blender with GoB and adjust rig angle very quickly
8. Return to Zbrush again and continue sculpting
9. If the mesh density is insufficient, increase the mesh density again with Blender and return to Zbrush. Go on sculpting again.

It's essentially like having a rigging function and vertex weight in Zbrush. This is a very important feature that increases the value of GoB.


------------------

By the way, I write down what I had thought for a long time. It would may be something useful.


Q1. What for using vertex groups?
 
At Blender2.8x, it has been shown in GoB Ver.3.3.6 that Face Maps can correctly represent the area of polygroups.

On the other hand,  vertex groups are not correctly  represent the area of polygroups. Isn't it the remnant of Blender 2.79 that used vertex groups to represent polygroups? In Blender 2.8x and above, it may not be necessary to use vertex groups that represent incorrect area as polygroups area.

If it is possible to generate polygroups area directly from Face Maps without using the vertex groups,  it may be simple to  generate the polygroups from Face Mpas, and use the vertex groups to keep the vertex weight information. 

For example, Face Maps are used for generating of polygroups area, and Vertex groups are used for storage of vertex weight information.
Normalization of vertex weight information (0 to 1) may be a specification that should be forced on the users, but I think that is acceptable.

What I mean is that the problem may be simpler if you don't use vertex groups for polygroups.

 (I'm not familiar with that data structures, so I might be saying something wrong, but please forgive me.)

--------------------

Q2. What for mask group?

About the entry of "mask" in vertex groups. I don't use the mask area with GoB addon, so I don't know much about its usefulness. Sometimes I've noticed that when I send a mesh from Blender to Zbrush, unintended areas have been masked sometimes, I guess it's a bug.

It may be a good idea to temporarily stop using the mask and try to isolate the problems.

I don't think you need to give special treatment to just the area of ​​the mask, because Zbrush can easily make a mask from a polygroup at any time if the polygroups are properly retained.

**Comment by Tsukasa-YAMATO** [comment] 2020-06-03 18:20
Dear Mr. Daniel, thank you for your reply.

Now I understood about Question 1 and I also understand it's difficult to balance the problem of the transition period of Blender and the correspondence of GoB.

Regarding Question 2, it's not really a big problem for me , just it's a suggestion that if it hinders the solution of the problem, you may be able to turn it off temporarily.

My biggest concern is "whether the weight information is maintained even if the mesh weight is returned again from Zbrush to Blender while maintaining the vertex weight information have been set in Blender".

Provisionally, I'm happy if that is feasible. I look forward to its implementation. And also many of my friends who are the professionals of figure creating are hope that.

**Comment by kromar** [comment] 2020-06-03 20:22
do not worry, if the topology is not changed the weight will be remaining on the mesh, this was already working at some point.

**Comment by Tsukasa-YAMATO** [comment] 2020-06-03 20:38
Really! It's great.
When I heard it, I can not help to want to try it as beta version.  :)
Please comment it to this thread again if it's available in even a beta version.
I am looking forward to it!

(But you don't have to publish in hurry. It's up to you. I will wait it.)

**Comment by kromar** [comment] 2020-06-04 10:24
i worked on a way of transferring the vertex groups and after understanding the issues it was quite simple to do maybe you can give it a try and let me know how it works out^^ 
Note: the **vertex group import is currently disabled in the preferences** so if you want to test that you need to enable it.

I tried a different approach that decides to which group a face should go if the **groups are overlapping,** so it might produce some strange results since i have only done some quick testing and im certain there are conditions that are not covered.


https://github.com/kromar/blender_GoB/tree/b3_3_7

**Comment by kromar** [comment] 2020-06-04 20:42
Take your time, im happy to wait a bit for your excellent feedback! 
I fixed another precision issue in that tag so it should only assign faces that have all their vertices in the group. i think the overlapping will just be a lucky thing at the moment but it might be possible to include weights in that assignment decision but might be a bit overkill.
![image](https://user-images.githubusercontent.com/1472884/83808102-7d049d80-a6b4-11ea-9a47-64cc51e7a1d1.png)

Meanwhile i will chip away on some of the mask bugs^^

**Comment by Tsukasa-YAMATO** [comment] 2020-06-05 08:36
Hi Daniel,
Thank you for publishing Ver.3.3.7.
I've confirmed that the vertex weight information is kept correctly during the round trip between Blender and Zbrush! Congrats! ! !

At the same time, I have also confirmed that by setting "From Face Maps" for the export setting in the preferences, the polygroup of Zbrush was kept correctly in both Blender and Zbrush. This is an ideal behavior.

GoB Ver.3.3.7 keeps polygroups as Face Maps and can now go back and forth between Zbrush and Blender while keeping vertex weight information in the vertex groups!

Great!!!

For me, I'm happy it has been achieved that both the vertex weight keeping and the correct keeping of the Zbrush polygroup area.

As I said before, I don't care about creating polygroups with vertex weights because I think it's enough if the polygroup area is generated from Face Maps( No need from vertex groups). Because the vertex groups do not always show the correct polygroup area, as you know before.

And I'm not interested in creating polygroups from vertex weights either. This is because polygroup "is often created with Zbrush and managed by the user" in order to make it easier to work with Zbrush, so I do not feel the need to automatically generate it based on Blender's vertex weight value.

(So, I feel that the behavior that changed the polygroup setting to "From Face Maps" from the initial setting of Ver.3.3.7 is already an ideal behavior. It’s enough for me with only the one setting’s changing.)


Rather, tell me, Daniel.
What is the purpose of creating a polygroup area from vertex weight information? 
(For many Zbrush users, it seems to be desirable that the setting to generate polygroups from Face Maps is the default. Rather, it's the problem  to overwrite  the user's original polygroup which they have prepared for easy working for Zbrush. )

I expect that many users don't like the specification.

Or is there a need from users for "users want to create a polygroup from vertex weights"? ( though I don't know it....)

-------

By the way, though the color of the polygroups are changed randomly every time with exporting to Zbrush, and I do not care much whether it is a specification or a bug. Color is not an issue, keeping the polygroup area itself is important.

Of course, if the colors are kept, I think it will be quite complete, but I think the priority is very low, minor issue.

**Comment by Tsukasa-YAMATO** [comment] 2020-06-05 12:07
Hi Daniel,
I have tested GoB Ver.3.3.7 with Blender 2.83.
(First of all, I'm testing the export settings for polygroups with "From Face Maps".)

--------------------

(Bug reports)

If "Mask" is set to OFF in the "Import" settings of preferences, neither vertex groups nor Face Maps are generated. When the mask is checked ON, it works correctly.

And also the similar problem occurs against the export settings.
If "Mask" is set to OFF in the "Export" settings of preferences, but mask is generated with Zbrush. (Try "CTRL + click the left button" just right after reloading the mesh with Zbrush.)

After intentionally masking on Zbrush and sending to Blender, unmask on Zbrush. Then, after confirming that the mask of Export setting is OFF, return to Zbrush and do CTRL + left click, the first mask area is restored. The annoyance is that the mask continues to work as a masked area as it was but  the mask is not displayed there (mask view mode is off right after when the mesh is back). I am very concerned about this issue. I hope the mesh will come back to Zbrush without the mask. Probably this is a bug. (The interim workaround is to run GoB after the users completely clear the mask.)

After all, the mask function seems to be the cause of something wrong.


---------------------

（Miscs）

For now Face Maps seems to be correctly reflected in Face Sets in sculpt mode.

**Comment by kromar** [comment] 2020-06-05 17:41
i forgot to mention this is not a release yet but a test version, i plan to do that once the mask and some other problems are fixed.

**Comment by Tsukasa-YAMATO** [comment] 2020-06-05 18:35
Dear Daniel,
Japan is 3 AM at midnight in weekend. I  will reply after 14 hours or later. Thank you for your quick response.

Please wait for a while to reply. :)

**Comment by Tsukasa-YAMATO** [comment] 2020-06-06 08:54
@kromar Thank you for your reply.

(This is about GoB Ver.3.3.7 beta version.)

>1

It's really great!!!

>2

Thank you for explaining how to use the vertex group. It seems to be a function for almost poly paint. And since it supported it in the past, it can be said that it is a remnant.
Face Maps has become an alternative method for polygroups, so it seems to be good with the current implementation where the usage can be divided between vertex groups and Face Maps at the user's will. I think that it is easier for you to isolate the problem when a bug occurs.

I'm looking forward to the stable version release. (I will continue testing using Ver.3.3.7 for a while.)

>3

Regarding the stabilization of the random color of the Polygroup, please recognize it "the specification" for the time being.  Memo it in far future request lists and FORGET it :)
Because it is NOT the essence of the tool, so I would like you to work on the improvement of the essential bug without using energy in a trivial issue.

>4

From now on, I will test with Blender 2.83.
I remember hearing from you before that there was no way to go back to Face Maps from Face Sets, but I'm glad I could confirm it. Let's wait and look forward to the future release of the Python specification!

>5

I'm glad to hear the prospect that the bug will be fixed. For the time being, I'll avoid it with your way.


As you pointed out, I tried turning on both "Mask" in the import and export settings, and when I tried, the mask state was reproduced correctly on Zbrush.

The problem arises with below.
1. Import mask is ON
2. Export mask is OFF

If you do this, you can not see the mask area when sending it back to Zbrush, but if you press CTRL + click in the background area of ​​the document of Zbrush, you can see that the mask area is generated. It's awkward to exist without being visible. (See in detail, https://github.com/JoseConseco/GoB/issues/99#issuecomment-639441965)

So for a while both will be turned on and continue testing Ver.3.3.7. It's no problem if the mask is visible correctly and no-existent with no-visible :)

(If the bug is fixed in the stable version, there is no problem. Perhaps I plan to use with the mask turned off for export in stable version.)

-----

This is just an idea, but for example, if you delete the import mask item and set it to always import it in inner working, it may be fine .
The interface has  only a mask checkbox for export.

And this item should be OFF by default. (If users use it for masking, look at Preferences and they will understand what it means immediately. And I think many users use this item with OFF.

-----

(Additional failure story)
For example, in Zbrush,  actually the body has masks scattered on the back of the body but I never noticed it at that time, and after moving the figure's body by Gizmo, then the feeling of despair is immeasurable :) , especially in case that it was found after few days without history.

Like that, invisible or unintended mask area is very troublesome. Cleared mask is simple and no problem.

-----
Conclusion

There are some minor bugs in Ver.3.3.7 but they can be avoided by users manually, and at the moment there are no fatal bugs, so I think that it can be used quite practically.
I will continue to use it.

If I find a bug, I will write it again.

**Comment by Tsukasa-YAMATO** [comment] 2020-06-06 09:46
Even if the mask items are set to ON for both import and export settings, the invisible mask area is generated in the Zbrush mesh by the operation of the following procedure.

1. After applying a mask with Zbrush, import it into Blender with GoB .
2. In the Zbrush window again, and clear the mask with CTRL + background **drag**.
3. Return to the Blender window again and export the mesh to Zbrush with GoB.
4. The mask area cannot be seen. (However, the mask area itself is reproduced.) You can see that the mask area itself is reproduced by inverting the mask area with CTRL + background **click**.
 
I think this is a control issue on the Zbrush side. Generally, CTRL + background drag clears the mask, but at this time, the mask display mode is set to "Hide". It means that the button of the attached image will be negative (gray). (On the other hand, when the user creates a mask, that button is automatically activated (orange).)

![2020-06-06_18h35_07](https://user-images.githubusercontent.com/65609416/83941210-94fb2f00-a824-11ea-8373-d3696dd1615d.jpg)


Even if the mask area is generated via macro or program means in this state, the mask area is no visible. (However, the mask area itself is generated.)

The problem is that it works as a mask even though it is invisible. (See (Additional failure story) of the previous comment.)

--------------------------

Can the GoB addon control the behavior of Zbrush after exporting the mesh from Blender to Zbrush? For example, is it possible for GoB addon to control "View Mask Button" to be enabled **after** Zbrush receives the mesh?

If you can't control that button, I think the safest way is to force the mask to clear and send to Zbrush.
Invisible masked areas are really troublesome.

**Comment by kromar** [comment] 2020-06-06 14:09
i noticed that issue with the ViewMask toggle in zbrush as well, this addon has no control over waht zbrush is doing, it can just provide the file that is sent to zbrush. so its not possible to change the state of that button as far as im aware.
I agree with your perspective and the conflicts in the workflow with the mask exchange so it will be important to be able to disable the mask exchange and i agree it should be disabled by default which is currently not possible.

**Comment by kromar** [comment] 2020-06-07 09:54
@Tsukasa-YAMATO it seems its possible to run Zscripts as post process, this would mean it should be possible to control the state of the masking button. i will give that a try, maybe this opens up a whole new layer of possibilities:D

**Comment by Tsukasa-YAMATO** [comment] 2020-06-07 12:23
@kromar 
That is good news.
However, if you try the implementation and it becomes too complicated, you may have better to move the issue to a future implementation plan.
This is because there are less people who currently expect the mask area to be restored, I guess. Many users think that if the mask is cleared off, that's enough.

(Of course the implementation testing is up to you. :) )

**Comment by kromar** [comment] 2020-06-09 17:56
@Tsukasa-YAMATO i disabled some of the options for the release that are not working or breaking transfers like the mask, so it will be enabled by default and i can take care of that in a later release.
i will make a release from v3_3_8 which you can find already here if you want to udpate to this version already: https://github.com/JoseConseco/GoB/tree/v3_3_8

**Comment by Tsukasa-YAMATO** [comment] 2020-06-09 18:16
@kromar Thanks Daniel,
I am happy that you are working for the release of GoB stable version. Japan is  at 3 o'clock in the midnight. I will test it after 14 hours or later and I'm going to report the results.
Please wait until then.
Cheers!

**Closed** 2021-02-27 12:12 UTC
Labels: bug, v3_3_8
