### ISSUE TITLE
Transform origin problem

### ISSUE THREAD

**Issue by SbstnDC** [JoseConseco/GoB#127] opened 2020-07-09 07:14 UTC
Hello everyone, when I send from zbrush to blender the transformation appears wrong, in blender a couple of units deviate from the origin, check the picture.

![image](https://user-images.githubusercontent.com/22725270/87008737-7cd05400-c1c4-11ea-8df9-29bdefa3d2d0.png)

**Comment by kromar** [comment] 2020-07-09 16:19
@SbstnDC  can you try the latest version from here https://github.com/JoseConseco/GoB/archive/GoZ-Blender_28.zip
i merged a fix for the position in there which should fix your problem.

**Comment by SbstnDC** [comment] 2020-07-11 12:07
it has not worked, when I send from blender to zbrush, or the other way around 4.4 units

![image](https://user-images.githubusercontent.com/22725270/87219179-66a7cc80-c359-11ea-84e5-69754686c405.png)

**Comment by kromar** [comment] 2020-07-11 12:34
@SbstnDC can you provide the exact steps that you do to reproduce this issue? and maybe provide a blend file to reproduce it? and please attach a screenshot of the GoB preferences so i can test the same configuration.

**Comment by SbstnDC** [comment] 2020-07-11 13:42
@kromar well, everyday use, no step other than creating and editing objects between blender and zbrush
![image](https://user-images.githubusercontent.com/22725270/87225130-206b6100-c38b-11ea-9fd2-e6339f9721a6.png)
i try fix manual all object but when send it all to zbrush, the list doesn't just finish sending everything
![image](https://user-images.githubusercontent.com/22725270/87225413-16e2f880-c38d-11ea-9a5b-4c6df8ceb3a7.png)

**Comment by SbstnDC** [comment] 2020-07-11 14:05
[MimicBook2.zip](https://github.com/JoseConseco/GoB/files/4906880/MimicBook2.zip)
HERE the file

**Comment by Tsukasa-YAMATO** [comment] 2020-07-11 15:17
@SbstnDC 
It's no problem in my environment. I transferred the Blender file to Zbrush with GoB and I have no problems. I couldn't reproduce the problem. The GoB add-on on your Blender may be corrupted. It is recommended to delete all GoB addons once, restart Blender, make sure the GoB addons are completely removed, and then install the latest GoB stable version and try it.
I'm pretty sure it's a problem from depending on  your environment. (I will not comment on this matter anymore.)

![2020-07-11_23h55_44](https://user-images.githubusercontent.com/65609416/87227005-c0001200-c3d2-11ea-9fe1-2e75f9968066.png)

-------------------------

My Environment
GoB 3.3.12
Blender 2.83.1
Zbrush 2020.1.4
Windows 10 Pro

----------------------

P.S.
If you want to get some useful information from someone, you should disclose the all information you can provide. Windows? Mac? What version of each software are you using? If you want free support, you should take it seriously about it! 

 (I will NOT comment on this matter anymore.)

**Comment by kromar** [comment] 2020-07-11 15:31
@SbstnDC  please zip the addon folder and upload it here before you delete it. it might help me find the issue if this is really the problem

**Comment by kromar** [comment] 2020-07-11 15:53
some information to the transfer of multiple object from blender to zbrush:
I have spent a significant amount of time trying to understand and fix some issues when transfering multiple objects but there seem to be some limitation on zbrush side that i can not fix within the blender addon and i can not ensure consistency. it might be that you run into another limitation that zbrush presents here.

I have talked with a pixologic dev how to solve it and am working now on a new way with zbrush scripts to bypass the GoZ import so i can define what zbrush should do, and not rely on the GoZ "blackbox". There seems to be some logic that i can not predict which i need to bypass.

Im currently experimenting with ZScripts since i have no experience with them, and so far it looks like i can use it to do all the importing. However it might be possible that i run into some issues which im not aware yet.

I know the issue you encountering at the moment makes the file exchange useless, but if the clean installation does not fix the problem you will probably have to wait for the first bypass import version.
The best thing a the moment is to **avoid multiple subtool transfers** from both sides, this seems to be the most reliable way at the moment, if you transfer multiple ones then you  get unpredictable behavior.

**Comment by SbstnDC** [comment] 2020-07-11 16:05
okay, here addon folder, thanks for the fast answer guys. 

I try clear my enviroment, and make a clean install.

[GoB-GoZ-Blender_28_2.zip](https://github.com/JoseConseco/GoB/files/4907086/GoB-GoZ-Blender_28_2.zip)

**Comment by SbstnDC** [comment] 2020-07-13 17:02
hello again, guys, how i can recover my goz gob, the tool is broken and I have already tried cleaning and reinstalling. I can't match the origins. HELP!

![image](https://user-images.githubusercontent.com/22725270/87332092-59e2ce80-c53b-11ea-85be-8ce421266d94.png)

**Comment by SbstnDC** [comment] 2020-07-13 17:07
My Environment
GoB 3.3.12 (latest now, 2020-07-13)
Blender 2.90
Zbrush 2020.1.4
Windows 10 Pro Workstations

**Comment by Tsukasa-YAMATO** [comment] 2020-07-13 18:16
![2020-07-14_03h11_13](https://user-images.githubusercontent.com/65609416/87338345-fd55d280-c57f-11ea-97c1-31bb56b09af0.png)


1. Load Dog template with Zbrush
2. GoZ transport and check the difference between in coordinates on Blender and Zbrush

Where is the world origin for you? Is it correct that your Zbrush's origin is really the world origin? Doesn't it show that the blender's world origin is correct? 

And Blender 2.90 is in alpha. No add-on developer can support the alpha version. Because "the specifications will change even tomorrow or day by day " is the alpha version.
Report the stable 2.83.2 results. The developers are not  members of customer support center. They are volunteers! Remember that. Bye.

**Comment by SbstnDC** [comment] 2020-07-13 18:53
When 
when i install gob the process durations ON option always appears. and every time I uninstall I will see the path C: \ Users \ SbstnDC \ AppData \ Roaming \ Blender Foundation \ Blender \ 2.90 \ scripts \ addons

![image](https://user-images.githubusercontent.com/22725270/87342060-e0eb7300-c54a-11ea-9629-44ca67c7fefa.png)


and everything is clean



THanks!, with there example works
Where is the world origin for you? 
yes
Is it correct that your Zbrush's origin is really the world origin? 
yes
Doesn't it show that the blender's world origin is correct?
yes

**Closed** 2021-02-27 12:13 UTC
Labels: bug, support
