### ISSUE TITLE
Blender 2.93 Alpha GoB error addons

### ISSUE THREAD

**Issue by mac4kent** [JoseConseco/GoB#216] opened 2021-02-27 14:23 UTC
Blender 2.93 Alpha on Add ons error while install button on GoB. See Youtube:
https://youtu.be/8UJeV8O_1pA
MacOS 11.3 Beta 2 (20E5186d) (February 17, 2021)

**Comment by kromar** [comment] 2021-02-27 15:01
thanks for reporting the issue i will look into it. does this also happen with blender 2.92? maybe its related to the python update in blender 2.93

**Comment by mac4kent** [comment] 2021-02-27 17:09
Yes Blender 2.92 Release it work on GoB as well.
Blender 2.93 Alpha is bug on GoB Add-ons.
https://builder.blender.org/download/

**Comment by kromar** [comment] 2021-02-27 17:43
Thanks for testing it, i will see if i can find out whats going wrong.

**Comment by kromar** [comment] 2021-02-27 17:58
@mac4kent can you try to install a other addon in blender 2.93 and see if that gives the error as well?
so far it looks like its some OSX restriction of relative paths and i suspect that its related to the blender python update. if that can be confirmed i can open a bug report so the devs can have a look at it.

**Comment by kromar** [comment] 2021-02-27 18:19
EDIT: please try the latest blender 2.93 version, apparently there was a fix for this issue.

**Comment by mac4kent** [comment] 2021-02-27 18:40
Let me check if date will change (February 28, 2021) tomorrow (Saturday)
Its doesn't change because of Mac only just only 1 Blender.app

**Comment by mac4kent** [comment] 2021-02-28 21:31
I just got download today Sunday, February 28, 2021 at 1:30 PM Pacific Time with Blender 2.93 Alpha.
Add-ons on GoB it work for sure.
Let's close the ticket.

**Comment by mac4kent** [comment] 2021-02-28 22:16
I just get download Blender 2.93 Alpha Sunday February 29, 2021 at about 1:00 PM Pacific Time.
Add-ons GoB it work
I notice click Export auto appear zBrush it work as well and Preferences > GoB auto appear Path Blender as well awesome make more easy much better than before.

Let's close the eicket.

**Comment by kromar** [comment] 2021-03-01 00:18
fantastic! thanks for letting me know and for reporting the issues!

**Closed by kromar** 2021-03-01 00:18 UTC

**Comment by mac4kent** [comment] 2021-03-26 12:28
Did not resolve yet.
First time click Export to zBrush it work.
Second time click Export to zBrush doesn't work
